### ISSUE TITLE
Can't compress empty file

### ISSUE THREAD

**Issue by winsoft666** [antony-jr/QArchive#50] opened 2021-12-28 11:45 UTC
Can't compress empty file( file size is 0 byte).

Maybe need comment [qarchivecompressor_p.cc#L618](https://github.com/antony-jr/QArchive/blob/035d2a8a205ea4841ca8389b365b8020e3a966c4/src/qarchivecompressor_p.cc#L618)

**Comment by antony-jr** [comment] 2021-12-28 11:51
I never saw the use case for compressing all empty files. Let me see.

**Comment by winsoft666** [comment] 2021-12-28 11:58
Right click desktop, create an new empty txt file, rename this file( just filename has a special meaning, file content is empty ), then compress this file to zip.

**Comment by antony-jr** [comment] 2021-12-28 12:09
Yeah I get the idea. The thing is why do we make an archive only consist of empty files? Anyways I think we should handle this case too. I will look into this.

**Comment by theLSB** [comment] 2022-12-09 16:28
The problem is not the fact it is not compressing, but that it hangs.
The use case is when for what ever reason files have been created with zero size (can happen if they are transferred via network for example, or the process died during file creation - this is how we noticed it).
I would be ok if QArchive throws an error in such a case - but not just hangs.

**Comment by antony-jr** [comment] 2022-12-09 16:44
Ok we can agree this is a bug. The fix should be hard.. let me work on this.

**Comment by antony-jr** [comment] 2022-12-19 19:27
Please use the latest master, you can now compress empty files.

**Closed by antony-jr** 2022-12-19 19:27 UTC
Labels: bug
