### ISSUE TITLE
TarFormat silently discards files larger than 9GB

### ISSUE THREAD

**Issue by dprotti** [antony-jr/QArchive#41] opened 2021-06-03 13:17 UTC
**Issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Issue**

Hi. The company for which I work (iRobot) is using QArchive to create among other things tarballs from large files.
QArchive succeeds to create `QArchive::TarFormat` files containing files under ~4~ 9GB in size each.
However if any file added to the .tar is larger than ~4~ 9GB then QArchive creates the .tar without reporting any error, but the resulting .tar in fact does not contain the file larger than ~4~ 9GB inside.

This is a bit critical for us since it's making loose valuable collected data inadvertently.
Let me know if I can help with more details.

**How to Reproduce the issue**

My tiny qarchive-test.cpp:
```
#include <iostream>
#include <QArchive/QArchive>
#include <QEventLoop>
#include <QtCore>

using QArchive::DiskCompressor;

class Task : public QObject
{
    Q_OBJECT
public:
    Task(QObject *parent = 0) : QObject(parent) {}

public slots:
    void run()
    {
        const QString tar_file("my_9GB.tar");
        DiskCompressor archiver(tar_file);
        QStringList entry_names({"some_9GB_file", "another_smaller_file"});
        archiver.addFiles(entry_names, {"/home/duilio/some_9GB_file", "/home/duilio/another_smaller_file"});
        archiver.setArchiveFormat(QArchive::TarFormat);
        QEventLoop loop;
        bool must_wait = true;
        bool archive_OK = false;

        QObject::connect(&archiver, &DiskCompressor::finished, [&]() {
            archive_OK = true;
            must_wait = false;
            loop.quit();
        });
        QObject::connect(&archiver, &DiskCompressor::error, [&](short code, QString file) {
            std::cerr << "Error archiving " << file.toStdString() << ": " << QArchive::errorCodeToString(code).toStdString() << std::endl;
            must_wait = false;
            loop.quit();
        });

        archiver.start();
        if (must_wait) {
            loop.exec();
        }

        emit finished();
    }

signals:
    void finished();
};

#include "qarchive-test.moc"

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    Task *task = new Task(&app);

    QObject::connect(task, &Task::finished, &app, &QCoreApplication::quit);
    QTimer::singleShot(0, task, SLOT(run()));

    return app.exec();
}
```

**Comment by antony-jr** [comment] 2021-06-03 16:01
I will look into this ASAP.

**Comment by antony-jr** [comment] 2021-06-03 16:19
@dprotti Have you tried the example program disk compressor? I just compressed a 7.8GB file in a tar with that example program. I will be investigating further. 

Can you tell me what OS are you in?

**Comment by dprotti** [comment] 2021-06-03 16:35
Thank you! I'll try your example program later today.

I'm using Ubuntu 18.04, Qt 5.9.5 and libarchive 3.4.0.

**Comment by antony-jr** [comment] 2021-06-03 16:37
@dprotti I can reproduce your issue with files 9GiB and larger.

**Comment by antony-jr** [comment] 2021-06-03 17:57
@dprotti The error seems to be with ustar format, the exact error can be found by executing the following command in bsdtar,

```
 $ bsdtar -c --format ustar -f test.tar some_big_file_9GB.img
 File size out of range
```

**Comment by antony-jr** [comment] 2021-06-03 17:57
But I think I need to add better error reporting.

**Comment by antony-jr** [comment] 2021-06-03 18:05
@dprotti The fix to this issue is to use **gnutar** format instead of **ustar** format. I will add extra formats and add more error checking in the upcoming fix.

```
 archive_write_set_format_gnutar(...);
 /// instead of 
 archive_write_set_format_ustar(...);
```

**Comment by antony-jr** [comment] 2021-06-03 19:19
@dprotti *Can you please try the master branch?* I've employed a fix.

**Comment by dprotti** [comment] 2021-06-04 13:56
Thanks! That works.
Could you please create a new release with the fix? Then we can pull in easily into our conan system.

Thanks again for your work on this.

**Comment by antony-jr** [comment] 2021-06-04 13:58
> Thanks! That works.
> Could you please create a new release with the fix? Then we can pull in easily into our conan system.
> 
> Thanks again for your work on this.

Okay.

**Closed** 2021-06-04 14:14 UTC
Labels: bug
